Update zfs-rclone-backup
combined functions into one script

diff --git a/zfs-rclone-backup b/zfs-rclone-backup
--- a/zfs-rclone-backup
+++ b/zfs-rclone-backup
@@ -5,34 +5,45 @@ server=$1
 pool=$2
 frequency=$4
 
-lastsnap=$(zfs holds `zfs list $pool/$volume -t snapshot -o name -s creation` 2>/dev/null | grep backup-rclone-$frequency | awk '{printf $1}' | tail -n 1)
-	if [ -z $lastsnap ]; then
-	  lastsnap=$(zfs holds `zfs list $pool/$volume -t snapshot -o name -s creation` 2>/dev/null | grep backup-rclone-monthly | awk '{printf $1}' | tail -n 1)
-	  zfs hold backup-rclone-$frequency $lastsnap
-	fi
+if [ $frequency == "daily" ]; then
+    lastsnap=$(zfs list $pool/$volume -t snapshot -o name -s creation -H 2>/dev/null | xargs zfs holds -H 2>/dev/null | grep backup-rclone | awk '{printf "%s\n",$1}' | tail -n 1)
+    if [ -z $lastsnap ]; then
+        echo "Could not find a recent snapshot with backup-rclone hold"
+        exit 55
+    fi
+elif [ $frequency == "monthly" ]; then
+    lastsnap=$(zfs list $pool/$volume -t snapshot -o name -s creation -H 2>/dev/null | xargs zfs holds -H 2>/dev/null | grep -E "backup-rclone-(monthly|yearly)" | awk '{printf "%s\n",$1}' | tail -n 1)
+    if [ -z $lastsnap ]; then
+        echo "Could not find a recent snapshot with backup-rclone hold"
+        exit 55
+    fi
+elif [ $frequency == "yearly" ]; then
+    lastsnap=$(zfs list $pool/$volume -t snapshot -o name -s creation -H 2>/dev/null | xargs zfs holds -H 2>/dev/null | grep backup-rclone-$frequency | awk '{printf "%s\n",$1}' | tail -n 1)
+fi
 
-	if [ -x $lastsnap ]; then
-	  lastsnap=$(zfs holds `zfs list $pool/$volume -t snapshot -o name -s creation` 2>/dev/null | grep backup-rclone-yearly | awk '{printf $1}' | tail -n 1)
-	  zfs hold backup-rclone-$frequency $lastsnap
-	fi
-
-	if [ -x $lastsnap ]; then
-	  lastsnap=$(zfs list -t snapshot $pool/$volume -o name -s creation | tail -n1)
-	  zfs hold backup-rclone-$frequency $lastsnap
-	fi
-
-newsnap=$(zfs list -t snapshot $pool/$volume -o name -s creation | grep $frequency | tail -n1)
-	if [ -z $newsnap ]; then
-	  newsnap=$(zfs list -t snapshot $pool/$volume -o name -s creation | tail -n1)
-	  zfs hold backup-rclone-$frequency $lastsnap
-	fi
+newsnap=$(zfs list -t snapshot $pool/$volume -o name -s creation -H | tail -n1)
 
 zfs hold backup-rclone-$frequency $newsnap
-zfs send -c -w -v -i $lastsnap $newsnap 2>/root/zfssend-$volume.log | rclone --config=/etc/rclone.conf --log-file=/root/rclonezfs-$volume.log rcat server-backup-crypt:zfs/$server/$pool/$volume/$newsnap-$frequency
+if [ $frequency == "yearly" ]; then
+    nice zfs send -c -w -v $newsnap 2>/root/zfssend-$volume.log | nice rclone --low-level-retries 99999 --retries-sleep 30m --config=/etc/rclone.conf --log-file=/root/rclonezfs-$volume.log rcat server-backup-crypt:zfs/$server/$newsnap-$frequency
+else
+    nice zfs send -c -w -v -i $lastsnap $newsnap 2>/root/zfssend-$volume.log | nice rclone --low-level-retries 99999 --retries-sleep 30m --config=/etc/rclone.conf --log-file=/root/rclonezfs-$volume.log rcat server-backup-crypt:zfs/$server/$newsnap-$frequency
+fi
 
 if [ $? == 0 ]; then
-  zfs list -t snapshot $pool/$volume -o name -S creation | grep $frequency | tail -n 2 | head -n 1 | awk '{printf $1}) | xargs xfs release backup-rclone-$frequency
-  if [ $frequency = "monthly" ]; then
-    zfs list -t snapshot $pool/$volume -o name -S creation | grep daily | awk '{printf $1}) | xargs xfs release backup-rclone-daily
-  fi
+    if [ $frequency == "yearly" ]; then
+        if [ $lastsnap ]; then
+            zfs list $pool/$volume -t snapshot -o name -s creation -H 2>/dev/null | xargs zfs holds -H 2>/dev/null | grep backup-rclone-monthly | awk '{printf "%s\n",$1}' | xargs zfs release backup-rclone-monthly
+            zfs list $pool/$volume -t snapshot -o name -s creation -H 2>/dev/null | xargs zfs holds -H 2>/dev/null | grep backup-rclone-daily | awk '{printf "%s\n",$1}' | xargs zfs release backup-rclone-daily
+            zfs list $pool/$volume -t snapshot -o name -s creation -H 2>/dev/null | xargs zfs holds -H 2>/dev/null | grep backup-rclone-yearly | sed -e '${d;}' | awk '{printf "%s\n",$1}' | xargs zfs release backup-rclone-yearly
+        fi
+    elif [ $frequency == "monthly" ]; then
+        zfs holds -H $lastsnap | grep -v "backup-rclone-daily" | awk '{printf "%s\n",$2}' | xargs -i zfs release "{}" $lastsnap
+    elif [ $frequency == "daily" ]; then
+        zfs list $pool/$volume -t snapshot -o name -s creation -H 2>/dev/null | xargs zfs holds -H 2>/dev/null | grep backup-rclone-daily | sed -e '${d;}' | awk '{printf "%s\n",$1}' | xargs zfs release backup-rclone-daily
+    fi
+else
+    zfs release backup-rclone-$frequency $newsnap
+    echo "Error sending dataset"
+    exit 69
 fi
